# This ansible script is used to configure two Dell Poweredge R210 machines. Both
# machines run Archlinux. The purpose is to learn how to configure ansible for
# mass deployment while maintaining a consistent state across machines.
---
- hosts: r210
  remote_user: root
  vars:
    ansible_python_interpreter: "/usr/bin/env python2"
  roles:
    - yaegashi.blockinfile

  tasks:
  - name: create a dummy file
    blockinfile:
      backup: yes
      create: yes
      dest: /root/{{ dummyfile }}
      content: "{{ dummyfile }}\nSincerely,\n\t{{ dummyauthor }}"
